# Generated by Django 5.2.4 on 2026-06-30 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ (ریال)')),
                ('status', models.CharField(choices=[('initiated', 'آغازشده'), ('paid', 'پرداخت\u200cشده'), ('failed', 'ناموفق'), ('refunded', 'بازگشت\u200cداده\u200cشده')], default='initiated', max_length=12, verbose_name='وضعیت')),
                ('backend', models.CharField(max_length=255, verbose_name='درگاه')),
                ('authority', models.CharField(blank=True, max_length=255, verbose_name='شناسهٔ مرجع درگاه')),
                ('ref_id', models.CharField(blank=True, max_length=255, verbose_name='کد پیگیری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='payments_pa_content_23405f_idx'), models.Index(fields=['authority'], name='payments_pa_authori_d17c7e_idx')],
            },
        ),
    ]
