# Generated by Django 5.2.4 on 2026-06-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='به\u200cصورت خودکار هنگام موفقیت پرداخت ثبت می\u200cشود.', null=True, verbose_name='زمان پرداخت'),
        ),
    ]
