# Generated by Django 5.2.4 on 2026-06-30 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_seed_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('species', models.CharField(help_text='مثلاً گربه، سگ، اسب', max_length=50, verbose_name='گونه')),
                ('sex', models.CharField(choices=[('male', 'نر'), ('female', 'ماده'), ('unknown', 'نامشخص')], default='unknown', max_length=10, verbose_name='جنسیت')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='وزن (کیلوگرم)')),
                ('photo', models.ImageField(blank=True, upload_to='animals/', verbose_name='عکس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('animal_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='catalog.animalcategory', verbose_name='دستهٔ حیوان')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'حیوان',
                'verbose_name_plural': 'حیوانات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Herd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='یک نام برای شناسایی گله، مثلاً «گلهٔ گوسفند شمالی»', max_length=100, verbose_name='عنوان گله')),
                ('species', models.CharField(help_text='مثلاً گوسفند، بز، شتر', max_length=50, verbose_name='گونه')),
                ('head_count', models.PositiveIntegerField(default=1, verbose_name='تعداد رأس')),
                ('farm_location', models.CharField(blank=True, max_length=255, verbose_name='موقعیت دامداری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('animal_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='herds', to='catalog.animalcategory', verbose_name='دستهٔ حیوان')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herds', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'گله',
                'verbose_name_plural': 'گله\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
