# Generated by Django 5.2.4 on 2026-07-01 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('message', models.TextField(verbose_name='پیام')),
                ('is_handled', models.BooleanField(default=False, verbose_name='رسیدگی\u200cشده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='دامپزشکی هیرکان', max_length=150, verbose_name='نام')),
                ('tagline', models.CharField(blank=True, default='درمانگاه و داروخانهٔ دامپزشکی در آمل و مازندران', max_length=255, verbose_name='شعار')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='تلفن ثابت')),
                ('mobile', models.CharField(blank=True, max_length=30, verbose_name='تلفن همراه')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('province', models.CharField(blank=True, default='مازندران', max_length=30, verbose_name='استان')),
                ('city', models.CharField(blank=True, default='آمل', max_length=80, verbose_name='شهر')),
                ('address', models.TextField(blank=True, verbose_name='نشانی')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='کد پستی')),
                ('hours', models.CharField(blank=True, default='هر روز ۹ تا ۲۰ — جمعه\u200cها تا ۱۴', max_length=255, verbose_name='ساعات کاری')),
                ('map_embed_url', models.URLField(blank=True, help_text='لینک نقشهٔ نشان یا گوگل برای نمایش موقعیت.', verbose_name='لینک نقشه')),
                ('about', models.TextField(blank=True, verbose_name='دربارهٔ ما')),
                ('terms', models.TextField(blank=True, help_text='متن قوانین و مقررات — برای نماد اعتماد الکترونیک لازم است.', verbose_name='قوانین و مقررات')),
                ('instagram', models.URLField(blank=True, verbose_name='اینستاگرام')),
                ('telegram', models.URLField(blank=True, verbose_name='تلگرام')),
                ('enamad_html', models.TextField(blank=True, help_text='کد HTML نماد؛ پس از دریافت e-Namad وارد شود.', verbose_name='کد نماد اعتماد الکترونیک')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مشخصات کسب\u200cوکار',
                'verbose_name_plural': 'مشخصات کسب\u200cوکار',
            },
        ),
    ]
