# Generated by Django 5.2.4 on 2026-06-30 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        ('catalog', '0003_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبدهای خرید',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('placed', 'ثبت\u200cشده'), ('approved', 'تأییدشده'), ('ready', 'آمادهٔ تحویل'), ('collected', 'تحویل\u200cشده'), ('cancelled', 'لغوشده')], default='placed', max_length=12, verbose_name='وضعیت')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت مشتری')),
                ('staff_note', models.TextField(blank=True, verbose_name='یادداشت کارمند')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='نام کالا')),
                ('unit_price', models.PositiveBigIntegerField(verbose_name='قیمت واحد (ریال)')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
            ],
            options={
                'verbose_name': 'قلم سفارش',
                'verbose_name_plural': 'اقلام سفارش',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(blank=True, max_length=255, verbose_name='دستور مصرف')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('refills_allowed', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تکرار مجاز')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ صدور')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='animals.animal', verbose_name='حیوان')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='صادرکننده')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='catalog.product', verbose_name='داروی نسخه\u200cای')),
            ],
            options={
                'verbose_name': 'نسخه',
                'verbose_name_plural': 'نسخه\u200cها',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='RefillRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('status', models.CharField(choices=[('requested', 'درخواست\u200cشده'), ('approved', 'تأییدشده'), ('declined', 'ردشده'), ('ready', 'آمادهٔ تحویل'), ('collected', 'تحویل\u200cشده'), ('cancelled', 'لغوشده')], default='requested', max_length=12, verbose_name='وضعیت')),
                ('price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت (ریال)')),
                ('staff_note', models.TextField(blank=True, verbose_name='یادداشت کارمند')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refill_requests', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refill_requests', to='pharmacy.prescription', verbose_name='نسخه')),
            ],
            options={
                'verbose_name': 'درخواست تکرار نسخه',
                'verbose_name_plural': 'درخواست\u200cهای تکرار نسخه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'قلم سبد',
                'verbose_name_plural': 'اقلام سبد',
                'constraints': [models.UniqueConstraint(fields=('cart', 'product'), name='uniq_cart_product')],
            },
        ),
    ]
