# Generated by Django 5.2.4 on 2026-07-01 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_service'),
        ('pharmacy', '0002_alter_cart_owner_alter_order_owner_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='uniq_cart_product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='pharmacy.prescription', verbose_name='نسخه'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='pharmacy.prescription', verbose_name='نسخه'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='حداکثر تعدادی که بیمار می\u200cتواند بر اساس این نسخه سفارش دهد.', verbose_name='تعداد مجاز'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product', 'prescription'), name='uniq_cart_product_rx'),
        ),
    ]
