# Generated by Django 5.2.4 on 2026-07-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_remove_cartitem_uniq_cart_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refillrequest',
            name='price',
        ),
        migrations.AddField(
            model_name='refillrequest',
            name='allowance_granted',
            field=models.BooleanField(default=False, verbose_name='مقدار اعمال شد'),
        ),
        migrations.AlterField(
            model_name='refillrequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='تعدادی که به مجاز نسخه افزوده می\u200cشود تا بیمار سفارش دهد.', verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='refillrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'درخواست\u200cشده'), ('approved', 'تأییدشده'), ('declined', 'ردشده'), ('cancelled', 'لغوشده')], default='requested', max_length=12, verbose_name='وضعیت'),
        ),
    ]
