# Generated by Django 5.2.4 on 2026-06-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=11, verbose_name='شماره موبایل')),
                ('code_hash', models.CharField(max_length=128)),
                ('purpose', models.CharField(choices=[('register', 'تأیید ثبت\u200cنام'), ('reset', 'بازیابی گذرواژه')], max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'کد یک\u200cبارمصرف',
                'verbose_name_plural': 'کدهای یک\u200cبارمصرف',
                'indexes': [models.Index(fields=['phone', 'purpose'], name='accounts_ph_phone_ccc62e_idx')],
            },
        ),
    ]
