# Generated by Django 5.2.4 on 2026-06-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_phoneotp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ownerprofile',
            options={'verbose_name': 'پروفایل مشتری', 'verbose_name_plural': 'پروفایل\u200cهای مشتریان'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'مشتری'), ('staff', 'همکار')], default='owner', max_length=10, verbose_name='نقش'),
        ),
    ]
