# Generated by Django 5.2.4 on 2026-06-30 22:13

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_ownerprofile_options_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='postal_code',
            field=models.CharField(blank=True, help_text='۱۰ رقم — برای ارسال سفارش\u200cها در آینده.', max_length=10, validators=[accounts.validators.validate_postal_code], verbose_name='کد پستی'),
        ),
    ]
