# Generated by Django 5.2.4 on 2026-06-30 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        ('catalog', '0004_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False, verbose_name='ویزیت آنلاین')),
                ('preferred_date', models.DateField(verbose_name='تاریخ پیشنهادی')),
                ('preferred_time_note', models.CharField(blank=True, help_text='مثلاً «صبح» یا «بعدازظهر»', max_length=100, verbose_name='بازهٔ زمانی پیشنهادی')),
                ('owner_note', models.TextField(blank=True, verbose_name='توضیح مالک')),
                ('confirmed_datetime', models.DateTimeField(blank=True, null=True, verbose_name='زمان تأییدشده')),
                ('staff_note', models.TextField(blank=True, verbose_name='یادداشت کارمند')),
                ('status', models.CharField(choices=[('requested', 'درخواست\u200cشده'), ('confirmed', 'تأییدشده'), ('completed', 'انجام\u200cشده'), ('cancelled', 'لغوشده'), ('no_show', 'عدم مراجعه')], default='requested', max_length=12, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='animals.animal', verbose_name='حیوان')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='catalog.service', verbose_name='خدمت')),
                ('vet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vet_appointments', to=settings.AUTH_USER_MODEL, verbose_name='دامپزشک')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
