# Generated by Django 5.2.4 on 2026-06-30 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='owner_note',
            field=models.TextField(blank=True, verbose_name='توضیح مشتری'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='staff_note',
            field=models.TextField(blank=True, verbose_name='یادداشت همکار'),
        ),
    ]
