# Generated by Django 5.2.4 on 2026-07-01 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_alter_animal_owner_alter_herd_owner'),
        ('appointments', '0002_alter_appointment_owner_alter_appointment_owner_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='herd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='animals.herd', verbose_name='گله'),
        ),
    ]
