# Generated by Django 5.2.4 on 2026-06-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='نامک')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='تصویر کاشی')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دستهٔ حیوان',
                'verbose_name_plural': 'دسته\u200cهای حیوان',
                'ordering': ['order', 'name'],
            },
        ),
    ]
