# Generated by Django 5.2.4 on 2026-06-30 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_seed_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('medication', 'دارو'), ('equipment', 'تجهیزات')], max_length=20, verbose_name='بخش')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='نامک')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت (ریال)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='تصویر')),
                ('is_prescription_only', models.BooleanField(default=False, help_text='فقط برای داروها؛ بدون نسخهٔ معتبر قابل سفارش نیست.', verbose_name='فقط با نسخه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('animal_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.animalcategory', verbose_name='دستهٔ حیوان')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالاها',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['animal_category', 'section', 'is_active'], name='catalog_pro_animal__039e69_idx')],
            },
        ),
    ]
