# Generated by Django 5.2.4 on 2026-06-30 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='نامک')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='مدت تقریبی (دقیقه)')),
                ('price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت تقریبی (ریال)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('animal_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='catalog.animalcategory', verbose_name='دستهٔ حیوان')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
                'ordering': ['name'],
            },
        ),
    ]
