# Generated by Django 5.2.4 on 2026-06-30 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        ('appointments', '0001_initial'),
        ('catalog', '0004_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=150, verbose_name='نام واکسن')),
                ('date_given', models.DateField(verbose_name='تاریخ تزریق')),
                ('next_due', models.DateField(blank=True, null=True, verbose_name='تاریخ نوبت بعدی')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('reminded_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان یادآوری')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='animals.animal', verbose_name='حیوان')),
            ],
            options={
                'verbose_name': 'واکسیناسیون',
                'verbose_name_plural': 'واکسیناسیون\u200cها',
                'ordering': ['-date_given'],
            },
        ),
        migrations.CreateModel(
            name='VisitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('notes', models.TextField(blank=True, verbose_name='شرح و توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_records', to='animals.animal', verbose_name='حیوان')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_records', to='appointments.appointment', verbose_name='نوبت')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_records', to='catalog.service', verbose_name='خدمت')),
                ('vet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_records', to=settings.AUTH_USER_MODEL, verbose_name='دامپزشک')),
            ],
            options={
                'verbose_name': 'پروندهٔ ویزیت',
                'verbose_name_plural': 'پرونده\u200cهای ویزیت',
                'ordering': ['-date'],
            },
        ),
    ]
