# Generated by Django 5.2.4 on 2026-06-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='next_due',
            field=models.DateField(blank=True, help_text='تنها تاریخی که باید وارد کنید. یادآوری پیامکی چند روز پیش از این تاریخ به\u200cصورت خودکار ارسال می\u200cشود؛ نیازی به تعیین زمان یادآوری نیست.', null=True, verbose_name='تاریخ نوبت بعدی'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='reminded_at',
            field=models.DateTimeField(blank=True, help_text='به\u200cصورت خودکار هنگام ارسال یادآوری ثبت می\u200cشود.', null=True, verbose_name='زمان ارسال یادآوری'),
        ),
    ]
